name: foundation_stereo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - scikit-image
    - omegaconf
    - opencv-contrib-python
    - imgaug
    - ninja
    - timm
    - albumentations
    - jupyterlab
    - scipy
    - joblib
    - scikit-learn
    - ruamel.yaml
    - trimesh
    - pyyaml
    - imageio
    - transformations
    - einops
    - gdown
    - nodejs
    - huggingface-hub
